### ISSUE TITLE
Heroku issues

### ISSUE THREAD

**Issue by leondrii** [iamkubi/pydactyl#20]
Hey guys,

When trying to turn on my bot on heroku it keeps getting this error message:

2020-11-23T15:15:17.772865+00:00 app[blazecraft.1]: discord.ext.commands.errors.ExtensionFailed: Extension 'comandos.minecraft.whitelist' raised an error: ModuleNotFoundError: No module named 'pydactyl.client'

I tried using the pydactyl module but then theres an error calling the 'PterodactylClient'
![download](https://user-images.githubusercontent.com/33943149/99979460-e2913700-2d85-11eb-9b51-b0ad61a4630b.png)

Can anyone help me please???

Thank you.

**Comment by leondrii** [comment]
This is the complete error message:

2020-11-23T15:25:54.565894+00:00 app[blazecraft.1]: Traceback (most recent call last):
2020-11-23T15:25:54.565897+00:00 app[blazecraft.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 607, in _load_from_module_spec
2020-11-23T15:25:54.566439+00:00 app[blazecraft.1]:     spec.loader.exec_module(lib)
2020-11-23T15:25:54.566440+00:00 app[blazecraft.1]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2020-11-23T15:25:54.566557+00:00 app[blazecraft.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-11-23T15:25:54.566674+00:00 app[blazecraft.1]:   File "/app/comandos/minecraft/whitelist.py", line 5, in <module>
2020-11-23T15:25:54.566793+00:00 app[blazecraft.1]:     from pydactyl import PterodactylClient
2020-11-23T15:25:54.566799+00:00 app[blazecraft.1]: ImportError: cannot import name 'PterodactylClient'
2020-11-23T15:25:54.566800+00:00 app[blazecraft.1]: 
2020-11-23T15:25:54.566805+00:00 app[blazecraft.1]: The above exception was the direct cause of the following exception:
2020-11-23T15:25:54.566805+00:00 app[blazecraft.1]: 
2020-11-23T15:25:54.566806+00:00 app[blazecraft.1]: Traceback (most recent call last):
2020-11-23T15:25:54.566808+00:00 app[blazecraft.1]:   File "main.py", line 85, in <module>
2020-11-23T15:25:54.566986+00:00 app[blazecraft.1]:     client.load_extension(f'comandos.minecraft.{filename[:-3]}')
2020-11-23T15:25:54.566996+00:00 app[blazecraft.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 664, in load_extension
2020-11-23T15:25:54.567567+00:00 app[blazecraft.1]:     self._load_from_module_spec(spec, name)
2020-11-23T15:25:54.567593+00:00 app[blazecraft.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 610, in _load_from_module_spec
2020-11-23T15:25:54.567978+00:00 app[blazecraft.1]:     raise errors.ExtensionFailed(key, e) from e
2020-11-23T15:25:54.567999+00:00 app[blazecraft.1]: discord.ext.commands.errors.ExtensionFailed: Extension 'comandos.minecraft.whitelist' raised an error: ImportError: cannot import name 'PterodactylClient
