### ISSUE TITLE
getting timeout when i do create_server action

### ISSUE THREAD

**Issue by vipvenom** [iamkubi/pydactyl#90]
```name = "admin server"
user_id = 10
nest_id=5
egg_id = 18
memory_limit=500
swap_limit = 0
disk_limit = 1500
query = api.servers.create_server(name, user_id, nest_id, egg_id, memory_limit, swap_limit, disk_limit, location_ids=[1], port_range=[], environment={}, cpu_limit=50, io_limit=500, database_limit=1, allocation_limit=0, backup_limit=0, docker_image=None, startup_cmd=None, dedicated_ip=False, start_on_completion=True, oom_disabled=True, default_allocation=None, additional_allocations=None, external_id=None, description=None)
````

ERROR

```Traceback (most recent call last):
  File "D:\flewcreate\FLEWCLOUD ACTIONS\actions.py", line 33, in <module>
    query = api.servers.create_server(name, user_id, nest_id, egg_id, memory_limit, swap_limit, disk_limit, location_ids=[1], port_range=[], environment={}, cpu_limit=50, io_limit=500, database_limit=1, allocation_limit=0, backup_limit=0, docker_image=None, startup_cmd=None, dedicated_ip=False, start_on_completion=True, oom_disabled=True, default_allocation=None, additional_allocations=None, external_id=None, description=None)
  File "C:\Users\adhee.LAPTOP-S8Q2UOU7\AppData\Local\Programs\Python\Python310\lib\site-packages\pydactyl\api\servers.py", line 304, in create_server
    response = self._api_request(endpoint='application/servers',
  File "C:\Users\adhee.LAPTOP-S8Q2UOU7\AppData\Local\Programs\Python\Python310\lib\site-packages\pydactyl\api\base.py", line 127, in _api_request
    response.raise_for_status()
  File "C:\Users\adhee.LAPTOP-S8Q2UOU7\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://panel.flewcloud.online/api/application/servers````

all latest version

**Comment by iamkubi** [comment]
That's a network issue that has nothing to do with pydactyl.
